modLoader="javafml"
loaderVersion="[49,)"
license="Custom license"
issueTrackerURL="https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
	modId="usefulslime"
	version="${version}"
	displayName="Useful Slime"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="http://curseforge.com/minecraft/mc-mods/useful-slime"
	logoFile="pack.png"
	credits="The people who suggested the mod to me and Tinkers Construct for the orignal mod"
	authors="MincraftEinstein"
	description='''
Adds some new uses for slime

License: https://github.com/MincraftEinstein/UsefulSlime/blob/main/LICENSE.md
'''

[modproperties.usefulslime]
    catalogueImageIcon="pack.png"

[[dependencies.usefulslime]]
    modId="forge"
    mandatory=true
    versionRange="[49.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="commonnetworking"
    mandatory=true
    versionRange="[1.0.10-1.20.2,)"
    ordering="NONE"
    side="BOTH"
