modLoader="javafml"
loaderVersion="[45,)"
license="Custom license"
issueTrackerURL="https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
	modId="usefulslime"
	version="${version}"
	displayName="Useful Slime"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="http://curseforge.com/minecraft/mc-mods/useful-slime"
	logoFile="logo.png"
	credits="The people who suggested the mod to me and Tinkers Construct for the orignal mod"
	authors="MincraftEinstein"
	description='''
Adds some new uses for slime

License:
The following files/specified lines/directories (on GitHub/in the project) are under the MIT license:
Common/src/main/java/einstein/usefulslime/items/SlimeSlingItem.java
Common/src/main/java/einstein/usefulslime/util/BounceHandler.java
Common/src/main/java/einstein/usefulslime/UsefulSlime.java (Lines 25 to 66)

The following files/specified lines/directories (in jars files) are under the MIT license:
einstein/usefulslime/items/SlimeSlingItem.java
einstein/usefulslime/util/BounceHandler.java
einstein/usefulslime/UsefulSlime.java (Lines 25 to 66)

All other files/lines of code/directories (both on GitHub/in the project/in jars) are under All Rights Reserved
'''

[modproperties.usefulslime]
    catalogueItemIcon="usefulslime:slimesling"

[[dependencies.usefulslime]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4, 1.20)"
    ordering="NONE"
    side="BOTH"