modLoader="javafml"
loaderVersion="[44,)"
license="Custom license"
issueTrackerURL="https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
	modId="usefulslime"
	version="${version}"
	displayName="Useful Slime"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="http://curseforge.com/minecraft/mc-mods/useful-slime"
	logoFile="logo.png"
	credits="The people who suggested the mod to me and Tinkers Construct for the orignal mod"
	authors="MincraftEinstein"
	description='''
Adds some new uses for slime

License:
The following directories (both in the jars and on GitHub) are under All Rights Reserved:
Common/src/main/resources
Forge/src/main/resources
Fabric/src/main/resources

All other directories and jars are under the MIT license
'''

[modproperties.usefulslime]
    catalogueItemIcon="usefulslime:slimesling"

[[dependencies.usefulslime]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3, 1.20)"
    ordering="NONE"
    side="BOTH"