modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="Custom license"
issueTrackerURL="https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
	modId="usefulslime"
	version="${version}"
	displayName="${mod_name}"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="http://curseforge.com/minecraft/mc-mods/useful-slime"
	logoFile="pack.png"
	credits="The people who suggested the mod to me and Tinkers Construct for the orignal mod"
	authors="${mod_author}"
	description="${description}"

[modproperties.usefulslime]
    catalogueImageIcon="pack.png"

[[dependencies.usefulslime]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="commonnetworking"
    mandatory=true
    versionRange="[${networking_version}-${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
