modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
	modId="usefulslime"
	version="1.7"
	displayName="Useful Slime"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="http://curseforge.com/minecraft/mc-mods/useful-slime"
	logoFile="logo.png"
	credits="The people who suggested the mod to me and Tinkers Construct for the orignal mod"
	authors="MinecraftEinstein"
	description='''
Adds some new uses for slime
'''

[modproperties.usefulslime]
    catalogueItemIcon="usefulslime:slimesling"

[[dependencies.usefulslime]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"