modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
	modId="usefulslime"
	version="1.3"
	displayName="Useful Slime"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="http://curseforge.com/minecraft/mc-mods/useful-slime"
	logoFile="logo.png"
	credits="The people who suggested the mod to me and Tinkers Construct for the orignal mod"
	authors="MinecraftEinstein"
	description='''
Adds some new uses for slime
'''

[modproperties.usefulslime]
    catalogueItemIcon="usefulslime:slimesling"

[[dependencies.usefulslime]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.usefulslime]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"
