modLoader = "javafml"
loaderVersion = "[1,)"
license = "Custom license"
issueTrackerURL = "https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
    modId = "usefulslime"
    version = "${version}"
    displayName = "Useful Slime"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL = "http://curseforge.com/minecraft/mc-mods/useful-slime"
    logoFile = "pack.png"
    credits = "The people who suggested the mod to me and Tinkers Construct for the orignal mod"
    authors = "MincraftEinstein"
    description = '''
Adds some new uses for slime

License: https://github.com/MincraftEinstein/UsefulSlime/blob/main/LICENSE.md
'''

[[mixins]]
    config = "usefulslime.mixins.json"

[[dependencies.usefulslime]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulslime]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.4]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulslime]]
    modId = "commonnetworking"
    type = "required"
    versionRange = "1.0.10-1.20.4"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulslime]]
    modId = "forgeconfigapiport"
    type = "required"
    versionRange = "[20.4.3,)"
    ordering = "NONE"
    side = "BOTH"
