modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "Custom license"
issueTrackerURL = "https://github.com/MincraftEinstein/UsefulSlime/issues"

[[mods]]
    modId = "usefulslime"
    version = "${version}"
    displayName = "${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL = "http://curseforge.com/minecraft/mc-mods/useful-slime"
    logoFile = "pack.png"
    credits = "The people who suggested the mod to me and Tinkers Construct for the orignal mod"
    authors = "${mod_author}"
    description = "${description}"

[[mixins]]
    config = "usefulslime.mixins.json"

[[dependencies.usefulslime]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulslime]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version}, ${max_minecraft_version})"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulslime]]
    modId = "commonnetworking"
    type = "required"
    versionRange = "[${networking_version}-${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.usefulslime]]
    modId = "forgeconfigapiport"
    type = "required"
    versionRange = "[${config_port_version},)"
    ordering = "NONE"
    side = "BOTH"
